[phases.setup]
nixPkgs = ['nodejs_20']
aptPkgs = []

[phases.install]
cmds = [
  'npm install --omit=dev --ignore-scripts --no-optional',
  'cd client && npm install --omit=dev'
]

[phases.build]
cmds = [
  'cd client && npm run build'
]

[start]
cmd = 'node server/index.js'
